{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-08T10:52:30Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix up the chart
    sha: 3d228e65743ee457daa7b3062f15c63786c65c15
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: add chart for verify pods
    sha: 934ca50aa8783ba866632c614e44132dd72ef3d1
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: add a verify pods command

      so that we can remove any pod thats failing to load the image

      as we sometimes see this issue on GCP if an image can't be pulled yet; removing the pod helps get k8s unstuck in BDD tests
    sha: e073c343395ec43097bc52ea7d644095dda12ded
  gitHttpUrl: https://github.com/jenkins-x/jx-verify
  gitOwner: jenkins-x
  gitRepository: jx-verify
  name: '{{ .Chart.Name }}'
  version: 0.0.53
status: {}
 
{{- end }}
