{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-11T13:01:27Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    branch: master
    committer:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    message: |
      chore: if domain is change.me or empty lets switch it to nip.io
    sha: 87af69da4db1d9912c8231b3ef904ea836e19d85
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: polish output
    sha: 6943883304cc9f00053dbc8bff3f467aea147b20
  gitHttpUrl: https://github.com/jenkins-x/jx-verify
  gitOwner: jenkins-x
  gitRepository: jx-verify
  name: '{{ .Chart.Name }}'
  version: 0.0.57
status: {}
 
{{- end }}
