{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-23T09:58:34Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix selector
    sha: e56f022ca2e16a5ac316c0ad7698658c2cc3cc25
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix selector
    sha: 7f65f019be81983bee90a878f4d2294a3488c316
  gitHttpUrl: https://github.com/jenkins-x/jx-verify
  gitOwner: jenkins-x
  gitRepository: jx-verify
  name: '{{ .Chart.Name }}'
  version: 0.0.68
status: {}
 
{{- end }}
