{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-10T07:37:46Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: polish output
    sha: 6943883304cc9f00053dbc8bff3f467aea147b20
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix verify job

      so that it properly waits for the job to actually start before tailing the log
    sha: ec5f9699f12e4958e0728b0d9c728ca7c824156f
  gitHttpUrl: https://github.com/jenkins-x/jx-verify
  gitOwner: jenkins-x
  gitRepository: jx-verify
  name: '{{ .Chart.Name }}'
  version: 0.0.56
status: {}
 
{{- end }}
